### ISSUE TITLE
Having Problem while Running it.

### ISSUE THREAD

**Issue by awais019** [MoonBlvd/tad-IROS2019#43]
I'm trying to run train_ego_pred but I get this error
Traceback (most recent call last):
  File "/home/dev007/Desktop/tad-IROS2019/train_ego_pred.py", line 41, in <module>
    val_gen = data.DataLoader(val_set, **dataloader_params)
  File "/home/dev007/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/dev007/.local/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by MoonBlvd** [comment]
Did you download the dataset properly? Why you have num_samples=0?

**Comment by awais019** [comment]
I just downloaded the A3D dataset
